import React, { useState, useEffect } from 'react';
import { supabase } from '../../config/supabase';

export const UserProfileSettings = ({ session }: { session: any }) => {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [profile, setProfile] = useState<any>(null);
  
  const [formData, setFormData] = useState({
    username: '',
    full_name: ''
  });

  useEffect(() => {
    if (!session?.user?.id) return;
    
    const fetchProfile = async () => {
      const { data, error } = await supabase
        .from('profiles')
        .select('*')
        .eq('id', session.user.id)
        .single();
        
      if (data) {
        setProfile(data);
        setFormData({
          username: data.username || '',
          full_name: data.full_name || ''
        });
      }
      setLoading(false);
    };
    
    fetchProfile();
  }, [session]);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!session?.user?.id) return;
    
    setSaving(true);
    const { error } = await supabase
      .from('profiles')
      .update({
        username: formData.username,
        full_name: formData.full_name
      })
      .eq('id', session.user.id);
      
    if (error) {
      alert(`Error updating profile: ${error.message}`);
    } else {
      alert('Profile updated successfully!');
      setProfile({ ...profile, ...formData });
    }
    setSaving(false);
  };

  if (loading) return <div style={{ padding: 40, color: 'var(--t3)' }}>Loading profile...</div>;

  return (
    <div className="page-scroll">
      <div className="page-content" style={{ maxWidth: 600 }}>
        <div style={{ marginBottom: 20 }}>
          <div className="page-title">Account Settings</div>
          <div className="page-desc">Manage your personal profile and display settings.</div>
        </div>
        
        <div className="card" style={{ padding: 24 }}>
          <form onSubmit={handleSave} style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            
            <div>
              <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: 'var(--t1)', marginBottom: 6 }}>Email Address (Login)</label>
              <input 
                className="inp" 
                value={session?.user?.email || ''} 
                disabled 
                style={{ background: 'var(--s2)', color: 'var(--t3)' }}
              />
              <div style={{ fontSize: 11, color: 'var(--t4)', marginTop: 4 }}>This is your primary login email. To change it, please contact your administrator.</div>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: 'var(--t1)', marginBottom: 6 }}>Connected Google Account (Outreach)</label>
              <input 
                className="inp" 
                value={profile?.google_email || 'Not connected'} 
                disabled 
                style={{ background: 'var(--s2)', color: 'var(--t3)' }}
              />
              <div style={{ fontSize: 11, color: 'var(--t4)', marginTop: 4 }}>To manage your connected Google account, go to System Settings {'>'} Integrations.</div>
            </div>

            <hr style={{ border: 0, borderTop: '1px solid var(--border-s)', margin: '8px 0' }} />

            <div>
              <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: 'var(--t1)', marginBottom: 6 }}>Display Name</label>
              <input 
                className="inp" 
                required
                value={formData.username} 
                onChange={e => setFormData({ ...formData, username: e.target.value })} 
                placeholder="e.g. John Doe"
              />
              <div style={{ fontSize: 11, color: 'var(--t4)', marginTop: 4 }}>Used for mentions and internal tags.</div>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: 'var(--t1)', marginBottom: 6 }}>Full Legal Name</label>
              <input 
                className="inp" 
                required
                value={formData.full_name} 
                onChange={e => setFormData({ ...formData, full_name: e.target.value })} 
                placeholder="e.g. Johnathan Doe"
              />
              <div style={{ fontSize: 11, color: 'var(--t4)', marginTop: 4 }}>Used on official quotes and contracts generated by the CRM.</div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 10 }}>
              <button type="submit" className="btn btn-primary" disabled={saving}>
                {saving ? 'Saving...' : 'Save Changes'}
              </button>
            </div>
            
          </form>
        </div>
      </div>
    </div>
  );
};
